from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
for name,link in [('README.md','docs/STREET_FRONTAGES_V32.md'),('AGENTS.md','docs/STREET_FRONTAGES_V32.md'),('assets/blender/README.md','../../docs/STREET_FRONTAGES_V32.md')]:
 p=ROOT/name;s=p.read_text(encoding='utf-8');prefix=f'[Latest street vehicles, furniture, opposite shopfront detail and videos]({link}).\n\nLatest Blender checkpoint: `assets/blender/pharmacie-street-frontages-v32.blend`.\nV31 vehicles and bounded street, V32 frontage relief/furniture/crossing approaches;\nv30 enclosed rear alley and prior pub/Taraj work retained. Zombies first,\npossible PvP later. Engine unchanged; Blender route checks are not game tests.\nSam explicitly requested pushing the completed mapping/media pass on 2026-10-04,\nsuperseding the earlier no-push instruction. Skeleton work is deferred.\n\n'
 if not s.startswith(prefix):p.write_text(prefix+s,encoding='utf-8')
p=ROOT/'scripts/open-blender.ps1';p.write_text(p.read_text().replace('pharmacie-zombies-alley-v30.blend','pharmacie-street-frontages-v32.blend'))
p=ROOT/'MODLOG.md';s=p.read_text();entry='''## 2026-10-04 — V31/V32 street mapping and shopfront detail

- Sam requested useful street vehicles/objects and a playable Zombies layout, with possible later PvP reuse. Built v31 from saved v30: four original modelled vehicles (hatchback, delivery van, damaged car, end wreck), closed road boundaries and service-lane gate, shallow planters/supply crates, entrance bollards and deep terrain backing. Stock BO3 civilian compact car source/textures/collision found locally; nothing copied into the repository or imported into the Blender checkpoint.
- Sam explicitly reaffirmed street detail over skeleton work, then requested further street/opposite-shop detail, a before/after video, general fly-through and a repo push. This latest explicit push request supersedes the earlier no-push preference. No game deployment or controls authorized here.
- V32 adds 227 original closed meshes: two wall-side benches, three bins, flush covers, road drain grilles, florist buckets/flowers, opposite shop plinths/sill trims/fascia relief/bulkheads/alarms/vents and four solid road-to-kerb approach wedges. Shop fittings and parking/closures are inferred gameplay dressing, not photo-confirmed reconstruction.
- Saved v31 and v32 checks pass: 572 retained pub/alley samples and 1,248 street-route samples, 0.42m radial clearance at three heights, 1.95m overhead probes. First trial straight opposite-pavement lines encountered existing bollards/pole: final route bends around them. Legacy floor classifier excluded 8cm kerb tops; support now explicitly includes upward-facing kerb/ramp hits. No claim of continuous capsule collision, engine stepping or AI navigation. Parent source hashes and all parent scene mesh geometry preserved; all 44 reference photo hashes unchanged. V31 330 and V32 227 new positive-volume/manifold solids checked. V31 preserves 8,879 parent scene meshes.
- Exact Blender background commands use build_street_combat_v31.py, check_street_combat_v31.py, render_street_combat_v31.py, build_frontage_detail_v32.py, check_frontage_detail_v32.py and render_frontage_detail_v32.py. Logs in ignored build/. V31 gallery video is 26s/720p/24fps/668,909 bytes; V32 comparison and continuous exterior flight are separate media artifacts. See docs/STREET_COMBAT_V31.md, docs/STREET_FRONTAGES_V32.md and their galleries/manifests.
- One bounded fal-ai/trellis-2 image-to-3D request completed as separately requested; generated static skeleton/chair GLB is local and deferred, not inserted into the scene or included in this push. Credentials read only from the user's external key file, never project files/logs. No credit purchase performed by the agent. No compiler, game test, engine conversion or deployment this pass.

'''
if entry not in s:p.write_text(s.replace('# Mod log\n\n','# Mod log\n\n'+entry,1))
