"""Reuse local comparison encoder, showing v30 -> v32 and v31 -> v32 details."""
from pathlib import Path
import ast,shutil
ROOT=Path(__file__).resolve().parents[1];dest=ROOT/'recon/v32'
shutil.copyfile(ROOT/'recon/v31/02_street_combat_before.png',dest/'02_initial_street_before.png')
s=(ROOT/'scripts/gallery_street_combat_v31.py').read_text();tree=ast.parse(s);node=next(n for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='segments' for t in n.targets));lines=s.splitlines()
segments=[('02_initial_street_before.png','BEFORE: street before vehicles and furniture',2),('02_street_combat_after.png','AFTER: vehicles, furniture and frontage relief',3),('02_street_combat_highlight.png','NEW detail pass highlighted in gold',3),('09_opposite_shop_detail_before.png','BEFORE: opposite shopfronts',3),('09_opposite_shop_detail_after.png','AFTER: lamps, trims, vents and flower displays',3),('10_fox_street_furniture_after.png','Wall-side benches and bins / clear pavement',3),('11_crossing_approach_after.png','Crossing approaches and drainage details',3),('07_lane_gate_after.png','Bounded service lane / future gameplay setup',3),('08_street_plan_highlight.png','New street details / clear circulation',3)]
lines[node.lineno-1:node.end_lineno]=['segments='+repr(segments)];s='\n'.join(lines).replace('recon/v31','recon/v32').replace('build/v31-video','build/v32-video').replace('Street mapping — v31','Street and shopfront mapping — v32').replace('Pharmacie v31','Pharmacie v32').replace('BLENDER v31','BLENDER v32').replace('V31_GALLERY_COMPLETE','V32_GALLERY_COMPLETE').replace('../../docs/STREET_COMBAT_V31.md','../../docs/STREET_FRONTAGES_V32.md')
s=s.replace('Existing 8cm kerb steps remain; dropped crossings need further mapping.','Solid approach ramps bridge the road-to-kerb rise at two crossings; game collision and stepping still need testing.')
s=s.replace('The road centre, pavements and crossings retain routes around the props.','Wall-side benches, bins, shopfront lamps, plinths, vents, alarm boxes and florist displays add another layer. Drain grilles and flush service covers detail the ground. The road centre, pavements and crossings retain routes around the props.')
s=s.replace("+''.join(sections)+'</main></html>'","+''.join(sections)+'<h2>Continuous exterior fly-through — 720p / 24fps</h2><p>28 seconds around the street, pub exterior and rear alley. A presentation camera flight, not a player traversal test.</p><video controls preload=\"metadata\"><source src=\"general-flythrough.webm\" type=\"video/webm\"></video><p><a href=\"general-flythrough.webm\" download>Download fly-through</a></p></main></html>'")
exec(compile(s,str(ROOT/'scripts/gallery_street_combat_v31.py'),'exec'))
