"""Compact labelled street comparison; rendered stills, not a fly-through."""
from pathlib import Path
import subprocess,json,html
from PIL import Image,ImageDraw,ImageFont
ROOT=Path(__file__).resolve().parents[1];dest=ROOT/'recon/v31';work=ROOT/'build/v31-video';work.mkdir(exist_ok=True)
segments=[('02_street_combat_before.png','BEFORE: open street',2),('02_street_combat_after.png','AFTER: staggered vehicles / clear escape routes',3),('02_street_combat_highlight.png','NEW street geometry highlighted in gold',3),('01_pub_vehicle_after.png','Parked car outside the pub / clear doorway',3),('03_van_and_pavement_after.png','Delivery van cover / open pavement',3),('04_wreck_crossing_after.png','Damaged car / crossing kept clear',3),('05_street_end_after.png','Wreck, roadblocks and closed street boundary',3),('07_lane_gate_after.png','Closed service-lane end / future reward proposal',3),('08_street_plan_highlight.png','Layout overview / Zombies first',3)]
font=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',28);small=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',18);clips=[]
for i,(name,title,duration) in enumerate(segments):
 im=Image.open(dest/name).convert('RGB');im.thumbnail((1280,650));canvas=Image.new('RGB',(1280,720),(17,22,27));canvas.paste(im,((1280-im.width)//2,0));d=ImageDraw.Draw(canvas);d.text((25,657),title,font=font,fill='white');d.text((25,697),'BLENDER v31 | street mapping review | engine conversion pending',font=small,fill=(172,190,200));p=work/f'{i:02d}.png';canvas.save(p);clip=work/f'{i:02d}.mp4';clips.append(clip)
 subprocess.run(['C:/ffmpeg/ffmpeg.exe','-hide_banner','-loglevel','error','-y','-loop','1','-framerate','24','-i',str(p),'-t',str(duration),'-vf',"zoompan=z='min(zoom+0.0004,1.02)':x='iw/2-iw/zoom/2':y='ih/2-ih/zoom/2':d=1:s=1280x720:fps=24",'-c:v','libx264','-preset','fast','-crf','24','-pix_fmt','yuv420p','-an',str(clip)],check=True)
concat=work/'clips.txt';concat.write_text(''.join("file '"+p.as_posix()+"'\n" for p in clips))
subprocess.run(['C:/ffmpeg/ffmpeg.exe','-hide_banner','-loglevel','error','-y','-f','concat','-safe','0','-i',str(concat),'-c:v','libvpx-vp9','-b:v','700k','-crf','32','-row-mt','1','-deadline','good','-cpu-used','4','-pix_fmt','yuv420p','-an',str(dest/'street-changes.webm')],check=True)
sections=[]
for p in sorted(dest.glob('*_after.png')):
 stem=p.stem[:-6];images=''
 for suffix,label in [('before','Before'),('after','After'),('highlight','New geometry in gold')]:
  f=dest/f'{stem}_{suffix}.png'
  if f.exists():images+=f'<figure><figcaption>{label}</figcaption><a href="{f.name}"><img loading="lazy" src="{f.name}"></a></figure>'
 sections.append(f'<section><h2>{html.escape(stem[3:].replace("_"," ").title())}</h2><div class="pair">{images}</div></section>')
validation=json.loads((dest/'validation.json').read_text());assert not validation['failures']
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pharmacie v31 street mapping</title><style>body{background:#15191e;color:#ecf0f3;font:17px system-ui;line-height:1.5;margin:0}main{max-width:1450px;padding:24px;margin:auto}a{color:#a9d4ff}video{width:100%;max-height:75vh}.pair{display:grid;grid-template-columns:repeat(auto-fit,minmax(400px,1fr));gap:14px}figure{margin:0}img{width:100%;border-radius:7px}section{margin:35px 0}.note{background:#283442;padding:16px;border-radius:8px}@media(max-width:650px){.pair{grid-template-columns:1fr}}</style><main><h1>Street mapping — v31</h1><p class="note">Four original vehicle props stagger the street: pub-side hatchback, delivery van, damaged car and a wreck at the closed end. Road barriers and service-lane gate define the boundaries; bollards, shallow planters and supply crates add frontage detail. The road centre, pavements and crossings retain routes around the props. Zombies comes first; PvP conversion is a later task.</p><p>Blender-only checkpoint. Gates, purchases, collision and zombie pursuit are not implemented or tested in BO3. Existing 8cm kerb steps remain; dropped crossings need further mapping. Vehicle placement is a gameplay adaptation, not photo-confirmed parking. Skeleton work is set aside.</p><h2>Changes video — 720p / 24fps</h2><p>26 seconds of labelled before/after views and highlights, animated from rendered stills.</p><video controls preload="metadata" poster="02_street_combat_after.png"><source src="street-changes.webm" type="video/webm"></video><p><a href="street-changes.webm" download>Download compact WebM</a> · <a href="../../docs/STREET_COMBAT_V31.md">Mapping notes</a> · <a href="../v30/index.html">Rear alley</a></p>'''+''.join(sections)+'</main></html>'
(dest/'index.html').write_text(page,encoding='utf-8')
probe=json.loads(subprocess.check_output(['C:/ffmpeg/ffprobe.exe','-v','error','-show_format','-show_streams','-of','json',str(dest/'street-changes.webm')]))
s=next(s for s in probe['streams'] if s['codec_type']=='video');assert (s['width'],s['height'],s['r_frame_rate'])==(1280,720,'24/1');assert abs(float(probe['format']['duration'])-26)<.1
meta=dict(bytes=(dest/'street-changes.webm').stat().st_size,duration=26,fps=24,resolution=[1280,720],style='Labelled still-based comparison with animated zooms; not continuous traversal');(dest/'video.json').write_text(json.dumps(meta,indent=2));print('V31_GALLERY_COMPLETE',meta)
